name = "Bootstrap-Squares"
license = "MIT"
licenselink = "https://github.com/Lerenn/hugo-theme-bootstrap-squares/blob/master/LICENSE"
description = ""
homepage = ""
tags = ["", ""]
features = ["", ""]
min_version = 0.13

[author]
  name = "Louis Fradin"
  homepage = "http://en.louis-fradin.net/"
